# StructuredText Example format.
# 
# Each comment line is stored in the
# special keyvars _COMMENT_n (unless disabled).
PROJECT_NAME: Seeking Dharma

TITLE: Aspects of Secularised Dharmas

DATESTAMP: 02/06/1957 02:00:00

LOCATION: Bali

# Blank lines between the keyvars above 
# are ignored.
# Blank lines in a multi-line keyvar 
# (like below) are *not* ignored.
DESCRIPTION: """
  
  Cherrypicking The Dharma?
  Yes. I mean No. I mean, "The" Dharma?
  There are many dharmas.  
  Not all have a capital D.
  And all have commonalities in values 
  and practice.
  So it's not really cherrypicking.
  It's more like pickpocketing.

  Pickpocketing from the various dharmas, 
  both the flawed and the admirable, 
  from ancient to present times, 
  from whoever they are, and 
  from wherever they may be.

  It's about selecting basic wisdoms 
  and practices, that most suit our own 
  conditions and paths,
  from the commonality of the global wise.

  This commonality is a great resource for
  developing resilient personal and group 
  dharmas that are able to influence and 
  guide with wisdom and compassion, as an 
  alternative to reactivity and hate.

"""

DEV_NOTE: """
  There is a limitation when assigning values 
  in multi-line keyvars where the value contains
  embedded triple-double-quotes (\""").

  Takeaway: Multi-line keyvar values need to 
  have embedded triple-double-quotes escaped, 
  eg, \"""
"""

# My ID!
ID: OKUSI420
